import type { WeatherMetadata } from '../util/WeatherMetadata.mjs';
import type { codes } from './codes.mjs';

/**
 * A mapping of WMO4677 code numbers to machine-readable metadata, useful e.g.
 * to present an appropriate graphical representation of a given code.
 */
export const metadata = {
  0: {
    code: 0,
    description: 'Cloud development not observed or observable',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'CLOUD_NOT_OBSERVED',
    precipitation: 'none',
    thunderstorm: false,
  },
  1: {
    code: 1,
    description: 'Clouds generally dissolving or becoming less developed',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'CLOUDS_DISSOLVING',
    precipitation: 'none',
    thunderstorm: false,
  },
  2: {
    code: 2,
    description: 'State of sky on the whole unchanged',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'CLOUDS_UNCHANGED',
    precipitation: 'none',
    thunderstorm: false,
  },
  3: {
    code: 3,
    description: 'Clouds generally forming or developing',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'CLOUDS_FORMING',
    precipitation: 'none',
    thunderstorm: false,
  },
  4: {
    code: 4,
    description: 'Visibility reduced by smoke',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'VISIBILITY_REDUCED_BY_SMOKE',
    precipitation: 'none',
    thunderstorm: false,
  },
  5: {
    code: 5,
    description: 'Haze',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'HAZE',
    precipitation: 'none',
    thunderstorm: false,
  },
  6: {
    code: 6,
    description:
      'Widespread dust in suspension in the air, not raised by wind at or near the station at the time of observation',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DUST_IN_SUSPENSION_NO_WIND',
    precipitation: 'none',
    thunderstorm: false,
  },
  7: {
    code: 7,
    description:
      'Dust or sand raised by wind at or near the station at the time of observation, but no well developed dust whirl(s) or sand whirl(s), and no duststorm or sandstorm seen',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DUST_OR_SAND_RAISED_BY_WIND_NO_STORM',
    precipitation: 'none',
    thunderstorm: false,
  },
  8: {
    code: 8,
    description:
      'Well developed dust whirl(s) or sand whirl(s) seen at or near the station during the preceding hour or at the time of observation, but no duststorm or sandstorm',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DUST_OR_SAND_WHIRLS_SEEN_NO_STORM',
    precipitation: 'none',
    thunderstorm: false,
  },
  9: {
    code: 9,
    description:
      'Duststorm or sandstorm within sight at the time of observation, or at the station during the preceding hour',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DUSTSTORM_OR_SANDSTORM_IN_SIGHT',
    precipitation: 'none',
    thunderstorm: false,
  },
  10: {
    code: 10,
    description: 'Mist',
    dustOrSandstorm: false,
    fogOrMist: true,
    key: 'MIST',
    precipitation: 'none',
    thunderstorm: false,
  },
  11: {
    code: 11,
    description:
      'Patches of shallow fog or ice fog at the station, whether on land or sea, not deeper than about 2 metres on land or 10 metres at sea',
    dustOrSandstorm: false,
    fogOrMist: true,
    key: 'SHALLOW_FOG_OR_ICE_FOG_PATCHES',
    precipitation: 'none',
    thunderstorm: false,
  },
  12: {
    code: 12,
    description:
      'More or less continuous shallow fog or ice fog at the station, whether on land or sea, not deeper than about 2 metres on land or 10 metres at sea',
    dustOrSandstorm: false,
    fogOrMist: true,
    key: 'CONTINUOUS_SHALLOW_FOG_OR_ICE_FOG',
    precipitation: 'none',
    thunderstorm: false,
  },
  13: {
    code: 13,
    description: 'Lightning visible, no thunder heard',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'LIGHTNING_VISIBLE_NO_THUNDER',
    precipitation: 'none',
    thunderstorm: false,
  },
  14: {
    code: 14,
    description:
      'Precipitation within sight, not reaching the ground or the surface of the sea',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'PRECIPITATION_WITHIN_SIGHT_NOT_REACHING_SURFACE',
    precipitation: 'none',
    thunderstorm: false,
  },
  15: {
    code: 15,
    description:
      'Precipitation within sight, reaching the ground or the surface of the sea, but distant, i.e. estimated to be more than 5 km from the station',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'PRECIPITATION_WITHIN_SIGHT_REACHING_GROUND_DISTANT',
    precipitation: 'none',
    thunderstorm: false,
  },
  16: {
    code: 16,
    description:
      'Precipitation within sight, reaching the ground or the surface of the sea, near to, but not at the station',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'PRECIPITATION_WITHIN_SIGHT_REACHING_GROUND_NEAR_BUT_NOT_AT_STATION',
    precipitation: 'none',
    thunderstorm: false,
  },
  17: {
    code: 17,
    description:
      'Thunderstorm, but no precipitation at the time of observation',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'THUNDERSTORM_NO_PRECIPITATION',
    precipitation: 'none',
    thunderstorm: true,
  },
  18: {
    code: 18,
    description:
      'Squalls at or within sight of the station during the preceding hour or at the time of observation',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SQUALLS_SEEN',
    precipitation: 'none',
    thunderstorm: false,
  },
  19: {
    code: 19,
    description:
      'Funnel clouds (tornado cloud or water spout) at or within sight of the station during the preceding hour or at the time of observation',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'FUNNEL_CLOUDS_SEEN',
    precipitation: 'none',
    thunderstorm: false,
  },
  20: {
    code: 20,
    description:
      'Drizzle (not freezing) or snow grains not falling as shower(s)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'PREV_HOUR_DRIZZLE_OR_SNOW_GRAINS',
    precipitation: 'in_preceding_hour',
    thunderstorm: false,
  },
  21: {
    code: 21,
    description: 'Rain (not freezing) not falling as shower(s)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'PREV_HOUR_RAIN_NO_SHOWERS',
    precipitation: 'in_preceding_hour',
    thunderstorm: false,
  },
  22: {
    code: 22,
    description: 'Snow not falling as shower(s)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'PREV_HOUR_SNOW_NO_SHOWERS',
    precipitation: 'in_preceding_hour',
    thunderstorm: false,
  },
  23: {
    code: 23,
    description: 'Rain and snow or ice pellets not falling as shower(s)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'PREV_HOUR_RAIN_AND_SNOW_OR_ICE_PELLETS',
    precipitation: 'in_preceding_hour',
    thunderstorm: false,
  },
  24: {
    code: 24,
    description: 'Freezing drizzle or freezing rain not falling as shower(s)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'PREV_HOUR_FREEZING_DRIZZLE_OR_RAIN',
    precipitation: 'in_preceding_hour',
    thunderstorm: false,
  },
  25: {
    code: 25,
    description: 'Shower(s) of rain',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'PREV_HOUR_SHOWER_OF_RAIN',
    precipitation: 'in_preceding_hour',
    thunderstorm: false,
  },
  26: {
    code: 26,
    description: 'Shower(s) of snow, or of rain and snow',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'PREV_HOUR_SHOWER_OF_SNOW_OR_RAIN_SNOW',
    precipitation: 'in_preceding_hour',
    thunderstorm: false,
  },
  27: {
    code: 27,
    description:
      'Shower(s) of hail, small hail, or snow pellets, or of rain and hail, small hail, or snow pellets',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'PREV_HOUR_SHOWER_OF_HAIL_OR_PELLETS',
    precipitation: 'in_preceding_hour',
    thunderstorm: false,
  },
  28: {
    code: 28,
    description: 'Fog or ice fog',
    dustOrSandstorm: false,
    fogOrMist: true,
    key: 'PREV_HOUR_FOG_OR_ICE_FOG',
    precipitation: 'in_preceding_hour',
    thunderstorm: false,
  },
  29: {
    code: 29,
    description: 'Thunderstorm (with or without precipitation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'PREV_HOUR_THUNDERSTORM',
    precipitation: 'in_preceding_hour',
    thunderstorm: false,
  },
  30: {
    code: 30,
    description:
      'Slight or moderate duststorm or sandstorm (has decreased during the preceding hour)',
    dustOrSandstorm: true,
    fogOrMist: false,
    key: 'SLIGHT_OR_MODERATE_DUSTSTORM_OR_SANDSTORM_DECREASING',
    precipitation: 'none',
    thunderstorm: false,
  },
  31: {
    code: 31,
    description:
      'Slight or moderate duststorm or sandstorm (no appreciable change during the preceding hour)',
    dustOrSandstorm: true,
    fogOrMist: false,
    key: 'SLIGHT_OR_MODERATE_DUSTSTORM_OR_SANDSTORM_NO_CHANGE',
    precipitation: 'none',
    thunderstorm: false,
  },
  32: {
    code: 32,
    description:
      'Slight or moderate duststorm or sandstorm (has begun or has increased during the preceding hour)',
    dustOrSandstorm: true,
    fogOrMist: false,
    key: 'SLIGHT_OR_MODERATE_DUSTSTORM_OR_SANDSTORM_INCREASING',
    precipitation: 'none',
    thunderstorm: false,
  },
  33: {
    code: 33,
    description:
      'Severe duststorm or sandstorm (has decreased during the preceding hour)',
    dustOrSandstorm: true,
    fogOrMist: false,
    key: 'SEVERE_DUSTSTORM_OR_SANDSTORM_DECREASING',
    precipitation: 'none',
    thunderstorm: false,
  },
  34: {
    code: 34,
    description:
      'Severe duststorm or sandstorm (no appreciable change during the preceding hour)',
    dustOrSandstorm: true,
    fogOrMist: false,
    key: 'SEVERE_DUSTSTORM_OR_SANDSTORM_NO_CHANGE',
    precipitation: 'none',
    thunderstorm: false,
  },
  35: {
    code: 35,
    description:
      'Severe duststorm or sandstorm (has begun or has increased during the preceding hour)',
    dustOrSandstorm: true,
    fogOrMist: false,
    key: 'SEVERE_DUSTSTORM_OR_SANDSTORM_INCREASING',
    precipitation: 'none',
    thunderstorm: false,
  },
  36: {
    code: 36,
    description:
      'Slight or moderate blowing snow generally low (below eye level)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SLIGHT_OR_MODERATE_BLOWING_SNOW_LOW',
    precipitation: 'none',
    thunderstorm: false,
  },
  37: {
    code: 37,
    description: 'Heavy drifting snow generally low (below eye level)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'HEAVY_DRIFTING_SNOW_LOW',
    precipitation: 'none',
    thunderstorm: false,
  },
  38: {
    code: 38,
    description:
      'Slight or moderate blowing snow generally high (above eye level)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SLIGHT_OR_MODERATE_BLOWING_SNOW_HIGH',
    precipitation: 'none',
    thunderstorm: false,
  },
  39: {
    code: 39,
    description: 'Heavy drifting snow generally high (above eye level)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'HEAVY_DRIFTING_SNOW_HIGH',
    precipitation: 'none',
    thunderstorm: false,
  },
  40: {
    code: 40,
    description:
      'Fog or ice fog at a distance at the time of observation, but not at the station during the preceding hour, the fog or ice fog extending to a level above that of the observer',
    dustOrSandstorm: false,
    fogOrMist: true,
    key: 'FOG_OR_ICE_FOG_AT_DISTANCE',
    precipitation: 'none',
    thunderstorm: false,
  },
  41: {
    code: 41,
    description: 'Fog or ice fog in patches',
    dustOrSandstorm: false,
    fogOrMist: true,
    key: 'FOG_OR_ICE_FOG_IN_PATCHES',
    precipitation: 'none',
    thunderstorm: false,
  },
  42: {
    code: 42,
    description:
      'Fog or ice fog, sky visible (has become thinner during the preceding hour)',
    dustOrSandstorm: false,
    fogOrMist: true,
    key: 'FOG_OR_ICE_FOG_SKY_VISIBLE_THINNING',
    precipitation: 'none',
    thunderstorm: false,
  },
  43: {
    code: 43,
    description:
      'Fog or ice fog, sky invisible (has become thinner during the preceding hour)',
    dustOrSandstorm: false,
    fogOrMist: true,
    key: 'FOG_OR_ICE_FOG_SKY_INVISIBLE_THINNING',
    precipitation: 'none',
    thunderstorm: false,
  },
  44: {
    code: 44,
    description:
      'Fog or ice fog, sky visible (no appreciable change during the preceding hour)',
    dustOrSandstorm: false,
    fogOrMist: true,
    key: 'FOG_OR_ICE_FOG_SKY_VISIBLE_NO_CHANGE',
    precipitation: 'none',
    thunderstorm: false,
  },
  45: {
    code: 45,
    description:
      'Fog or ice fog, sky invisible (no appreciable change during the preceding hour)',
    dustOrSandstorm: false,
    fogOrMist: true,
    key: 'FOG_OR_ICE_FOG_SKY_INVISIBLE_NO_CHANGE',
    precipitation: 'none',
    thunderstorm: false,
  },
  46: {
    code: 46,
    description:
      'Fog or ice fog, sky visible (has begun or has become thicker during the preceding hour)',
    dustOrSandstorm: false,
    fogOrMist: true,
    key: 'FOG_OR_ICE_FOG_SKY_VISIBLE_THICKENING',
    precipitation: 'none',
    thunderstorm: false,
  },
  47: {
    code: 47,
    description:
      'Fog or ice fog, sky invisible (has begun or has become thicker during the preceding hour)',
    dustOrSandstorm: false,
    fogOrMist: true,
    key: 'FOG_OR_ICE_FOG_SKY_INVISIBLE_THICKENING',
    precipitation: 'none',
    thunderstorm: false,
  },
  48: {
    code: 48,
    description: 'Fog, depositing rime, sky visible',
    dustOrSandstorm: false,
    fogOrMist: true,
    key: 'FOG_DEPOSITING_RIME_SKY_VISIBLE',
    precipitation: 'none',
    thunderstorm: false,
  },
  49: {
    code: 49,
    description: 'Fog, depositing rime, sky invisible',
    dustOrSandstorm: false,
    fogOrMist: true,
    key: 'FOG_DEPOSITING_RIME_SKY_INVISIBLE',
    precipitation: 'none',
    thunderstorm: false,
  },
  50: {
    code: 50,
    description:
      'Drizzle, not freezing, intermittent (slight at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DRIZZLE_NOT_FREEZING_INTERMITTENT_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['drizzle'],
    precipitation: 'current',
    primaryPrecipitationType: 'drizzle',
    thunderstorm: false,
  },
  51: {
    code: 51,
    description:
      'Drizzle, not freezing, continuous (slight at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DRIZZLE_NOT_FREEZING_CONTINUOUS_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['drizzle'],
    precipitation: 'current',
    primaryPrecipitationType: 'drizzle',
    thunderstorm: false,
  },
  52: {
    code: 52,
    description:
      'Drizzle, not freezing, intermittent (moderate at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DRIZZLE_NOT_FREEZING_INTERMITTENT_MODERATE',
    possiblePrecipitationSeverities: ['moderate'],
    possiblePrecipitationTypes: ['drizzle'],
    precipitation: 'current',
    primaryPrecipitationType: 'drizzle',
    thunderstorm: false,
  },
  53: {
    code: 53,
    description:
      'Drizzle, not freezing, continuous (moderate at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DRIZZLE_NOT_FREEZING_CONTINUOUS_MODERATE',
    possiblePrecipitationSeverities: ['moderate'],
    possiblePrecipitationTypes: ['drizzle'],
    precipitation: 'current',
    primaryPrecipitationType: 'drizzle',
    thunderstorm: false,
  },
  54: {
    code: 54,
    description:
      'Drizzle, not freezing, intermittent (heavy or dense at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DRIZZLE_NOT_FREEZING_INTERMITTENT_HEAVY',
    possiblePrecipitationSeverities: ['heavy'],
    possiblePrecipitationTypes: ['drizzle'],
    precipitation: 'current',
    primaryPrecipitationType: 'drizzle',
    thunderstorm: false,
  },
  55: {
    code: 55,
    description:
      'Drizzle, not freezing, continuous (heavy or dense at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DRIZZLE_NOT_FREEZING_CONTINUOUS_HEAVY',
    possiblePrecipitationSeverities: ['heavy'],
    possiblePrecipitationTypes: ['drizzle'],
    precipitation: 'current',
    primaryPrecipitationType: 'drizzle',
    thunderstorm: false,
  },
  56: {
    code: 56,
    description: 'Drizzle, freezing, slight',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DRIZZLE_FREEZING_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['drizzle'],
    precipitation: 'current',
    primaryPrecipitationType: 'drizzle',
    thunderstorm: false,
  },
  57: {
    code: 57,
    description: 'Drizzle, freezing, moderate or heavy (dense)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DRIZZLE_FREEZING_MODERATE_OR_HEAVY',
    possiblePrecipitationSeverities: ['moderate', 'heavy'],
    possiblePrecipitationTypes: ['drizzle'],
    precipitation: 'current',
    primaryPrecipitationType: 'drizzle',
    thunderstorm: false,
  },
  58: {
    code: 58,
    description: 'Drizzle and rain, slight',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DRIZZLE_AND_RAIN_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['drizzle', 'rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  59: {
    code: 59,
    description: 'Drizzle and rain, moderate or heavy',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DRIZZLE_AND_RAIN_MODERATE_OR_HEAVY',
    possiblePrecipitationSeverities: ['moderate', 'heavy'],
    possiblePrecipitationTypes: ['drizzle', 'rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  60: {
    code: 60,
    description:
      'Rain, not freezing, intermittent (slight at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_NOT_FREEZING_INTERMITTENT_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  61: {
    code: 61,
    description:
      'Rain, not freezing, continuous (slight at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_NOT_FREEZING_CONTINUOUS_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  62: {
    code: 62,
    description:
      'Rain, not freezing, intermittent (moderate at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_NOT_FREEZING_INTERMITTENT_MODERATE',
    possiblePrecipitationSeverities: ['moderate'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  63: {
    code: 63,
    description:
      'Rain, not freezing, continuous (moderate at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_NOT_FREEZING_CONTINUOUS_MODERATE',
    possiblePrecipitationSeverities: ['moderate'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  64: {
    code: 64,
    description:
      'Rain, not freezing, intermittent (heavy at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_NOT_FREEZING_INTERMITTENT_HEAVY',
    possiblePrecipitationSeverities: ['heavy'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  65: {
    code: 65,
    description:
      'Rain, not freezing, continuous (heavy at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_NOT_FREEZING_CONTINUOUS_HEAVY',
    possiblePrecipitationSeverities: ['heavy'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  66: {
    code: 66,
    description: 'Rain, freezing, slight',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_FREEZING_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  67: {
    code: 67,
    description: 'Rain, freezing, moderate or heavy (dense)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_FREEZING_MODERATE_OR_HEAVY',
    possiblePrecipitationSeverities: ['moderate', 'heavy'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  68: {
    code: 68,
    description: 'Rain or drizzle and snow, slight',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_OR_DRIZZLE_AND_SNOW_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['rain', 'drizzle', 'snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  69: {
    code: 69,
    description: 'Rain or drizzle and snow, moderate or heavy',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_OR_DRIZZLE_AND_SNOW_MODERATE_OR_HEAVY',
    possiblePrecipitationSeverities: ['moderate', 'heavy'],
    possiblePrecipitationTypes: ['drizzle', 'rain', 'snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  70: {
    code: 70,
    description:
      'Intermittent fall of snowflakes (slight at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOWFLAKES_INTERMITTENT_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  71: {
    code: 71,
    description:
      'Continuous fall of snowflakes (slight at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOWFLAKES_CONTINUOUS_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  72: {
    code: 72,
    description:
      'Intermittent fall of snowflakes (moderate at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOWFLAKES_INTERMITTENT_MODERATE',
    possiblePrecipitationSeverities: ['moderate'],
    possiblePrecipitationTypes: ['snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  73: {
    code: 73,
    description:
      'Continuous fall of snowflakes (moderate at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOWFLAKES_CONTINUOUS_MODERATE',
    possiblePrecipitationSeverities: ['moderate'],
    possiblePrecipitationTypes: ['snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  74: {
    code: 74,
    description:
      'Intermittent fall of snowflakes (heavy at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOWFLAKES_INTERMITTENT_HEAVY',
    possiblePrecipitationSeverities: ['heavy'],
    possiblePrecipitationTypes: ['snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  75: {
    code: 75,
    description: 'Continuous fall of snowflakes (heavy at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOWFLAKES_CONTINUOUS_HEAVY',
    possiblePrecipitationSeverities: ['heavy'],
    possiblePrecipitationTypes: ['snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  76: {
    code: 76,
    description: 'Diamond dust (with or without fog)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DIAMOND_DUST',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['ice'],
    precipitation: 'current',
    primaryPrecipitationType: 'ice',
    thunderstorm: false,
  },
  77: {
    code: 77,
    description: 'Snow grains (with or without fog)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOW_GRAINS',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  78: {
    code: 78,
    description: 'Isolated star-like snow crystals (with or without fog)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'ISOLATED_STAR_LIKE_SNOW_CRYSTALS',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  79: {
    code: 79,
    description: 'Ice pellets',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'ICE_PELLETS',
    possiblePrecipitationSeverities: ['heavy', 'moderate', 'slight', 'violent'],
    possiblePrecipitationTypes: ['ice'],
    precipitation: 'current',
    primaryPrecipitationType: 'ice',
    thunderstorm: false,
  },
  80: {
    code: 80,
    description: 'Rain shower(s), slight',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_SHOWERS_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  81: {
    code: 81,
    description: 'Rain shower(s), moderate or heavy',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_SHOWERS_MODERATE_OR_HEAVY',
    possiblePrecipitationSeverities: ['moderate', 'heavy'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  82: {
    code: 82,
    description: 'Rain shower(s), violent',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_SHOWERS_VIOLENT',
    possiblePrecipitationSeverities: ['violent'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  83: {
    code: 83,
    description: 'Shower(s) of rain and snow mixed, slight',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_AND_SNOW_MIXED_SHOWERS_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['rain', 'snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  84: {
    code: 84,
    description: 'Shower(s) of rain and snow mixed, moderate or heavy',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_AND_SNOW_MIXED_SHOWERS_MODERATE_OR_HEAVY',
    possiblePrecipitationSeverities: ['moderate', 'heavy'],
    possiblePrecipitationTypes: ['rain', 'snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  85: {
    code: 85,
    description: 'Snow shower(s), slight',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOW_SHOWERS_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  86: {
    code: 86,
    description: 'Snow shower(s), moderate or heavy',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOW_SHOWERS_MODERATE_OR_HEAVY',
    possiblePrecipitationSeverities: ['moderate', 'heavy'],
    possiblePrecipitationTypes: ['snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  87: {
    code: 87,
    description:
      'Shower(s) of snow pellets or small hail, with or without rain or rain and snow mixed (slight)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOW_PELLETS_OR_SMALL_HAIL_SHOWERS_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['hail', 'rain', 'snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  88: {
    code: 88,
    description:
      'Shower(s) of snow pellets or small hail, with or without rain or rain and snow mixed (moderate or heavy)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOW_PELLETS_OR_SMALL_HAIL_SHOWERS_MODERATE_OR_HEAVY',
    possiblePrecipitationSeverities: ['moderate', 'heavy'],
    possiblePrecipitationTypes: ['hail', 'rain', 'snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  89: {
    code: 89,
    description:
      'Shower(s) of hail, small hail, or snow pellets, with or without rain or rain and snow mixed, not associated with thunder (slight)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'HAIL_SMALL_HAIL_OR_SNOW_PELLETS_SHOWERS_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['hail', 'rain', 'snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'hail',
    thunderstorm: false,
  },
  90: {
    code: 90,
    description:
      'Shower(s) of hail, small hail, or snow pellets, with or without rain or rain and snow mixed, not associated with thunder (moderate or heavy)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'HAIL_SMALL_HAIL_OR_SNOW_PELLETS_SHOWERS_MODERATE_OR_HEAVY',
    possiblePrecipitationSeverities: ['moderate', 'heavy'],
    possiblePrecipitationTypes: ['hail', 'rain', 'snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'hail',
    thunderstorm: false,
  },
  91: {
    code: 91,
    description:
      'Slight rain at time of observation (thunderstorm during the preceding hour but not at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SLIGHT_RAIN_AFTER_THUNDERSTORM',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  92: {
    code: 92,
    description:
      'Moderate or heavy rain at time of observation (thunderstorm during the preceding hour but not at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'MODERATE_OR_HEAVY_RAIN_AFTER_THUNDERSTORM',
    possiblePrecipitationSeverities: ['moderate', 'heavy'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  93: {
    code: 93,
    description:
      'Slight snow, or rain and snow mixed or hail, small hail, or snow pellets at time of observation (thunderstorm during the preceding hour but not at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SLIGHT_SNOW_RAIN_SNOW_MIXED_OR_HAIL_AFTER_THUNDERSTORM',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['hail', 'rain', 'snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  94: {
    code: 94,
    description:
      'Moderate or heavy snow, or rain and snow mixed or hail, small hail, or snow pellets at time of observation (thunderstorm during the preceding hour but not at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'MODERATE_OR_HEAVY_SNOW_RAIN_SNOW_MIXED_OR_HAIL_AFTER_THUNDERSTORM',
    possiblePrecipitationSeverities: ['moderate', 'heavy'],
    possiblePrecipitationTypes: ['hail', 'rain', 'snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  95: {
    code: 95,
    description:
      'Thunderstorm, slight or moderate, without hail but with rain and/or snow at time of observation (thunderstorm at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'THUNDERSTORM_SLIGHT_MODERATE_NO_HAIL',
    possiblePrecipitationSeverities: ['slight', 'moderate'],
    possiblePrecipitationTypes: ['rain', 'snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: true,
  },
  96: {
    code: 96,
    description:
      'Thunderstorm, slight or moderate, with hail, small hail, or snow pellets at time of observation (thunderstorm at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'THUNDERSTORM_SLIGHT_MODERATE_WITH_HAIL',
    possiblePrecipitationSeverities: ['slight', 'moderate'],
    possiblePrecipitationTypes: ['hail'],
    precipitation: 'current',
    primaryPrecipitationType: 'hail',
    thunderstorm: true,
  },
  97: {
    code: 97,
    description:
      'Thunderstorm, heavy, without hail, small hail, or snow pellets but with rain and/or snow at time of observation',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'THUNDERSTORM_HEAVY_NO_HAIL',
    possiblePrecipitationSeverities: ['heavy'],
    possiblePrecipitationTypes: ['rain', 'snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: true,
  },
  98: {
    code: 98,
    description:
      'Thunderstorm combined with duststorm or sandstorm at time of observation (thunderstorm at time of observation)',
    dustOrSandstorm: true,
    fogOrMist: false,
    key: 'THUNDERSTORM_WITH_DUST_OR_SANDSTORM',
    precipitation: 'none',
    thunderstorm: true,
  },
  99: {
    code: 99,
    description:
      'Thunderstorm, heavy, with hail, small hail, or snow pellets at time of observation (thunderstorm at time of observation)',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'THUNDERSTORM_HEAVY_WITH_HAIL',
    possiblePrecipitationSeverities: ['heavy'],
    possiblePrecipitationTypes: ['hail'],
    precipitation: 'current',
    primaryPrecipitationType: 'hail',
    thunderstorm: true,
  },
} as const satisfies WeatherMetadata<typeof codes>;
