import type { WeatherMetadata } from '../util/WeatherMetadata.mjs';
import type { codes } from './codes.mjs';

/**
 * A mapping of [open-meteo](https://open-meteo.com/) code numbers to
 * machine-readable metadata, useful e.g. to present an appropriate graphical
 * representation of a given code.
 */
export const metadata = {
  0: {
    code: 0,
    description: 'Clear sky',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'CLEAR_SKY',
    precipitation: 'none',
    thunderstorm: false,
  },
  1: {
    code: 1,
    description: 'Mainly clear',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'MAINLY_CLEAR',
    precipitation: 'none',
    thunderstorm: false,
  },
  2: {
    code: 2,
    description: 'Partly cloudy',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'PARTLY_CLOUDY',
    precipitation: 'none',
    thunderstorm: false,
  },
  3: {
    code: 3,
    description: 'Overcast',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'OVERCAST',
    precipitation: 'none',
    thunderstorm: false,
  },
  45: {
    code: 45,
    description: 'Fog',
    dustOrSandstorm: false,
    fogOrMist: true,
    key: 'FOGGY',
    precipitation: 'none',
    thunderstorm: false,
  },
  48: {
    code: 48,
    description: 'Depositing rime fog',
    dustOrSandstorm: false,
    fogOrMist: true,
    key: 'DEPOSITING_RIME_FOG',
    precipitation: 'none',
    thunderstorm: false,
  },
  51: {
    code: 51,
    description: 'Light drizzle',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DRIZZLE_LIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['drizzle'],
    precipitation: 'current',
    primaryPrecipitationType: 'drizzle',
    thunderstorm: false,
  },
  53: {
    code: 53,
    description: 'Moderate drizzle',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DRIZZLE_MODERATE',
    possiblePrecipitationSeverities: ['moderate'],
    possiblePrecipitationTypes: ['drizzle'],
    precipitation: 'current',
    primaryPrecipitationType: 'drizzle',
    thunderstorm: false,
  },
  55: {
    code: 55,
    description: 'Dense drizzle',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'DRIZZLE_DENSE',
    possiblePrecipitationSeverities: ['heavy'],
    possiblePrecipitationTypes: ['drizzle'],
    precipitation: 'current',
    primaryPrecipitationType: 'drizzle',
    thunderstorm: false,
  },
  56: {
    code: 56,
    description: 'Light freezing drizzle',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'FREEZING_DRIZZLE_LIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['drizzle'],
    precipitation: 'current',
    primaryPrecipitationType: 'drizzle',
    thunderstorm: false,
  },
  57: {
    code: 57,
    description: 'Dense freezing drizzle',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'FREEZING_DRIZZLE_DENSE',
    possiblePrecipitationSeverities: ['heavy'],
    possiblePrecipitationTypes: ['drizzle'],
    precipitation: 'current',
    primaryPrecipitationType: 'drizzle',
    thunderstorm: false,
  },
  61: {
    code: 61,
    description: 'Slight rain',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  63: {
    code: 63,
    description: 'Moderate rain',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_MODERATE',
    possiblePrecipitationSeverities: ['moderate'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  65: {
    code: 65,
    description: 'Heavy rain',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_HEAVY',
    possiblePrecipitationSeverities: ['heavy'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  66: {
    code: 66,
    description: 'Light freezing rain',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'FREEZING_RAIN_LIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  67: {
    code: 67,
    description: 'Heavy freezing rain',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'FREEZING_RAIN_HEAVY',
    possiblePrecipitationSeverities: ['heavy'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  71: {
    code: 71,
    description: 'Slight snow',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOW_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  73: {
    code: 73,
    description: 'Moderate snow',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOW_MODERATE',
    possiblePrecipitationSeverities: ['moderate'],
    possiblePrecipitationTypes: ['snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  75: {
    code: 75,
    description: 'Heavy snow',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOW_HEAVY',
    possiblePrecipitationSeverities: ['heavy'],
    possiblePrecipitationTypes: ['snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  77: {
    code: 77,
    description: 'Snow grains',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOW_GRAINS',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  80: {
    code: 80,
    description: 'Slight rain showers',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_SHOWERS_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  81: {
    code: 81,
    description: 'Moderate rain showers',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_SHOWERS_MODERATE',
    possiblePrecipitationSeverities: ['moderate'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  82: {
    code: 82,
    description: 'Violent rain showers',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'RAIN_SHOWERS_VIOLENT',
    possiblePrecipitationSeverities: ['violent'],
    possiblePrecipitationTypes: ['rain'],
    precipitation: 'current',
    primaryPrecipitationType: 'rain',
    thunderstorm: false,
  },
  85: {
    code: 85,
    description: 'Slight snow showers',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOW_SHOWERS_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  86: {
    code: 86,
    description: 'Heavy snow showers',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'SNOW_SHOWERS_HEAVY',
    possiblePrecipitationSeverities: ['heavy'],
    possiblePrecipitationTypes: ['snow'],
    precipitation: 'current',
    primaryPrecipitationType: 'snow',
    thunderstorm: false,
  },
  95: {
    code: 95,
    description: 'Slight or moderate thunderstorm',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'THUNDERSTORM_SLIGHT_OR_MODERATE',
    precipitation: 'none',
    thunderstorm: true,
  },
  96: {
    code: 96,
    description: 'Thunderstorm with slight hail',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'THUNDERSTORM_HAIL_SLIGHT',
    possiblePrecipitationSeverities: ['slight'],
    possiblePrecipitationTypes: ['hail'],
    precipitation: 'current',
    primaryPrecipitationType: 'hail',
    thunderstorm: true,
  },
  99: {
    code: 99,
    description: 'Thunderstorm with heavy hail',
    dustOrSandstorm: false,
    fogOrMist: false,
    key: 'THUNDERSTORM_HAIL_HEAVY',
    possiblePrecipitationSeverities: ['heavy'],
    possiblePrecipitationTypes: ['hail'],
    precipitation: 'current',
    primaryPrecipitationType: 'hail',
    thunderstorm: true,
  },
} as const satisfies WeatherMetadata<typeof codes>;
